import i18n from 'i18next'
import ReactDOM from 'react-dom/client'
import { initReactI18next } from 'react-i18next'
import App from './App'
import './index.css'

i18n.use(initReactI18next).init({
	resources: {
		English: {
			translations: {
				Vodkino: 'Vodka Flavors',
				Port: 'Port 🍇',
				Arak: 'Arak 🌿',
				Beer: 'Beer 🍺',
				Vodka: 'Vodka ❄️',
				spirits: 'Vodka with flavors 🍒',
				'product.article.VodkaMoskva': 'Vodka Moskva is a premium vodka from Israel with 35% alcohol strength and 175ml volume.',	
				'product.article.VodkaManhattan': 'Vodka Manhattan is a premium vodka from Israel with 37.5% alcohol strength and 700ml volume.',
				'product.article.VodkaIcePalace500': 'Vodka Ice Palace 500ml is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaPrimeBlanche': 'Vodka Prime Blanche is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaPrimeNoir': 'Vodka Prime Noir is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaIcePalace': 'Vodka Ice Palace is a premium vodka from Ukraine with 40% alcohol strength and 1L volume.',
				'product.article.VodkaNepoborna': 'Vodka Nepoborna is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.portoCabracoRuby': 'It is a rich red port wine with bright fruit notes, the bottle volume is 750 ml.',
                'product.article.Taller': 'A refreshing beer with a smooth taste.',
                'product.article.CognacSikvaruli': 'A fine cognac with a rich aroma and smooth finish.',
                'product.article.CognacSikvaruli5': 'A premium cognac aged for 5 years with a deep, complex flavor.',
                'product.article.VodkaRussianStandart1894': 'A classic Russian vodka with a clean, crisp taste.',
				'product.article.EichbaumHell': 'A classic German Helles beer with a smooth and refreshing taste.',
        'product.article.EichbaumPilsener': 'A crisp and clean German Pilsener with a balanced bitterness.',
        'product.article.Superior': 'A rich and robust Irish stout with deep malt flavors.',
				'product.article.oceaniusProdutoDePortugal2019': 'This is an exquisite wine, combining fresh fruit notes and softness characteristic of Portuguese wines',
				'Warning about alcohol': 'Alcohol is harmful to your health!',
				Wine: 'Wine 🍷',
				Cognac: 'Cognac 🥂',
				'product.article.portoCabracoRose': 'It is a refreshing pink port wine with fruity aromas and the bottle volume is 750 ml.',
				'product.article.portoCabracoWhite': 'It is a white port wine with a mild and sweet flavor and the bottle volume is 750 ml.',
				productarticlfiuzaChardonnayArinto:
					'This creamy wine, dominated by Chardonnay and a fraction of Arinto.',
					'product.article.fiuzaNativeReserva2018': 'This is an elegant wine with a rich taste, where the notes of the cartoon dominate, complemented by the exquisite freshness of Arinto.',
				warning:
					'Warning: Excessive alcohol consumption can be harmful to your health. Please drink responsibly.',
					'product.article.portoCabracoRuby': 'It is a rich red port wine with bright fruit notes, the bottle volume is 750 ml.'
			},
		},
		Русский: {
			translations: {
				Description: 'Описание',
				HOME: 'ГЛАВНАЯ',
				CATALOG: 'КАТАЛОГ',
				CONTACT: 'КОНТАКТЫ',
				'ALL PRODUCTS': 'ВСЕ ПРОДУКТЫ',
				'More Details': 'Подробнее',
				'Bottle Volume': 'Объем бутылки',
				Origin: 'Страна',
				'Alcohol Strength': 'Содержание алкоголя',
				'Alcohol 🍾': 'Алкоголь 🍾',
				Portugal: 'Португалия',
				'Show All Results': 'ВСЕ РЕЗУЛЬТАТЫ',
				spirits: 'Водка со вкусами 🍒',
				Search: 'Поиск',
				Port: 'Портвейн 🍇',
				'product.article.VodkaMoskva': 'Водка Москва - это премиальная водка из Израиля с крепостью 35% и объемом 175 мл.',
				'product.article.VodkaManhattan': 'Водка Манхэттен - это премиальная водка из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.VodkaIcePalace500': 'Водка Айс Палас 500 мл - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaPrimeBlanche': 'Водка Прайм Бланш - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaPrimeNoir': 'Водка Прайм Нуар - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaIcePalace': 'Водка Айс Палас - это премиальная водка из Украины с крепостью 40% и объемом 1 литр.',
				'product.article.VodkaNepoborna': 'Водка Непоборна - это премиальная водка из Украины с крепостью 40% и объемом 700 мл',
				'product.article.EichbaumHell': 'Классическое немецкое светлое пиво с мягким и освежающим вкусом.',
        'product.article.EichbaumPilsener': 'Чистый и освежающий немецкий пилснер с сбалансированной горечью.',
        'product.article.Superior': 'Богатый и крепкий ирландский стаут с глубокими солодовыми нотами.',
				'product.article.oceaniusProdutoDePortugal2019': 'Это изысканное вино, сочетающее в себе свежие фруктовые ноты и мягкость, характерную для португальских вин',
				'product.article.fiuzaNativeReserva2018': 'Это элегантное вино с насыщенным вкусом, где доминируют ноты Шардоне, дополненные изысканной свежестью Аринто.',
				'Warning about alcohol': 'Алкоголь вреден для вашего здоровья!',
				'Wine Fiuza Chardonnay Arinto Native Reserva 2017': 'Вино Fiuza Chardonnay Arinto Native Reserva 2017',
				'productdetailsfiuzaChardonnayArinto': 'dda',
				'Port wine Cabraco Ruby': 'Портвейн Cabraco Ruby',
				'Port wine Cabraco White': 'Портвейн Cabraco White',
				'Port wine Cabraco Rose': 'Портвейн Cabraco Rose',
				'Cognac Maxime Trijol': 'Коньяк Maxime Trijol',
				'Cognac Maxime Trijol Vsop': 'Коньяк Maxime Trijol Vsop',
				'Cognac Maxime Trijol Small': 'Коньяк Maxime Trijol Small',
				'Wine Fiuza Native Reserva 2018': 'Вино Fiuza Native Reserva 2018',
				'Wine Oceanius Produto De Portugal 2019':
					'Вино Oceanius Produto De Portugal 2019',
				'Wine Fiuza Cabernet Sauvignon': 'Вино Fiuza Cabernet Sauvignon',
				'Wine Adega De Borba': 'Вино Adega De Borba',
				'Wine Fiuza Merilot 2015': 'Вино Fiuza Merilot 2015',
				'Wine Montes Carlos DOCA lentejo Tinto2016':
					'Вино Montes Carlos DOCA lentejo Tinto2016',
				'Wine Bianco Chardonnay AllSeasons Collection 2020':
					'Вино Bianco Chardonnay AllSeasons Collection 2020',
				'Wine Spain Velas Corsarias': 'Вино Spain Velas Corsarias',
				'Wine Summer Merlot AllSeasons Collection 2020':
					'Вино Summer Merlot AllSeasons Collection 2020',
				'Cognac Maxime Trijol 3L': 'Коньяк Maxime Trijol 3L',

				'Learn More': 'Узнать больше',
				Search: 'Поиск',
				'Cognac Maxime Trijol Eiffel Tower': 'Коньяк Maxime Trijol Eiffel Tower',
				'Discover the Finest Alcoholic Beverages at R.I.L.L Collection':
					'Откройте для себя лучшие алкогольные напитки в R.I.L.L Collection',
				'Best Alcohol from all over the world': 'Лучший алкоголь со всего мира',
				'Open Catalog': 'ВЕСЬ КАТАЛОГ',
				Catalog: 'Каталог',
				'Get In Touch': 'Свяжитесь с нами',
				'We are in Facebook, Tiktok, & Instagram. You can also contact us via Email.':
					'Мы есть в Facebook, Tiktok и Instagram. Вы также можете связаться с нами по электронной почте.',
				'Page Not Found': 'Страница не найдена',
				'Go Back Home': 'Вернутся назад',
				'Contact Us': 'Свяжитесь с нами',
				Contact: 'Контакты',
				Reviews: 'Отзывы',
				Insights: 'Идеи',
				Permalinks: 'Постоянные ссылки',
				Blog: 'Блог',
				Beer: 'Пиво 🍺',
				Vodka: 'Водка ❄️',
				'Port wine': 'Портвейн',
				Wine: 'Вино 🍷',
				Arak: 'Арак 🌿',
				'product.article.portoCabracoRose': 'Это освежающий розовый портвейн с фруктовыми ароматами, объем бутылки составляет 750 мл.',
				'product.article.portoCabracoWhite': 'Это белый портвейн с мягким и сладким вкусом, объем бутылки составляет 750 мл.',
				warning:
					'Внимание: Чрезмерное употребление алкоголя вредит вашему здоровью.',
				Cognac: 'Коньяк 🥂',
				'Popular product categories': 'Популярные категории товаров',
				Communities: 'Сообщество',
				'product.article.portoCabracoRuby': 'Это насыщенный красный портвейн с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'Our Socials and contacts.': 'Наши социальные сети и контакты.',
				'Import and marketing of quality products.':
					'Импорт и реализация качественной продукции.',
				'Street 8 Azur': 'Улица 8 Азур',
				'Postal code 5802920, Israel': 'Почтовый индекс 5802920, Израиль',
				'Phone ☎: 03-6542200 Mobile 📱: 052-4448940':
					'Телефон ☎: 03-6542200 Мобильный 📱: 052-4448940',
				'Email: rillcollection2023@gmail.com':
					'Электронная почта: rillcollection2023@gmail.com',
				Home: 'Главная',
				'Welcome!': 'Добро пожаловать!',
				'Verify that you are legal age.':
					'Убедитесь, что вы достигли совершеннолетия.',
				"I'm above 18": 'Мне больше 18',
				"I'm under 18": 'Мне меньше 18',
				'All Categories': 'Все Категории',
				arak: 'Арак',
				'Warning: contains alcohol, it is recommended to avoid excessive drinking':
					'Внимание: содержит алкоголь, рекомендуется избегать чрезмерного употребления.',
				'Warning! Excessive consumption of alcohol is life-threatening and harmful to health':
					'Предупреждение! Чрезмерное употребление алкоголя опасно для жизни и вредно для здоровья',
				wine: 'Вино',
				portWine: 'Портвейн',
				producttitlefiuzaChardonnayArinto: 'Fiuza Chardonnay Arinto',
				cognac: 'Коньяк',
				productarticlfiuzaChardonnayArinto:
					'Это сливочное вино с преобладанием Шардоне и долей Аринто. ',
			},
		},
		עברית: {
			translations: {
				Beer: 'בִּירָה 🍺',
				Vodka: 'ווֹדקָה ❄️',
				Wine: 'יַיִן 🍷',
				wine: 'יַיִן 🍷',
				Arak: 'ערק 🌿',
				spirits: 'וודקה עם טעמים 🍒',
				Cognac: 'קוניאק 🥂',
				Port: 'יַיִן פּוֹרט 🍇',
				HOME: 'בַּיִת',
				CATALOG: 'קָטָלוֹג',
				CONTACT: 'צור קשר',
				'ALL PRODUCTS': 'כל המוצרים',
				Description: 'תֵאוּר',
				'More Details': 'פרטים נוספים',
				'Alcohol Strength': 'כוח אלכוהול',
				Origin: 'מָקוֹר',
				'Bottle Volume': 'נפח בקבוקים',
				'product.article.VodkaMoskva': 'וודקה מוסקבה היא וודקה פרימיום מישראל עם 35% אלכוהול ונפח של 175 מ"ל.',
				'product.article.VodkaManhattan': 'וודקה מנהטן היא וודקה פרימיום מישראל עם 37.5% אלכוהול ונפח של 700 מ"ל.',
				'product.article.VodkaIcePalace500': 'וודקה אייס פאלאס 500 מ"ל היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 500 מ"ל.',
				'product.article.VodkaPrimeBlanche': 'וודקה פריים בלאנש היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 500 מ"ל.',
				'product.article.VodkaPrimeNoir': 'וודקה פריים נואר היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 500 מ"ל.',
				'product.article.VodkaIcePalace': 'וודקה אייס פאלאס היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 1 ליטר.',
				'product.article.VodkaNepoborna': 'וודקה נפובורנה היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.EichbaumHell': 'בירה גרמנית קלאסית עם טעם חלק ומרענן.',
        'product.article.EichbaumPilsener': 'פילזנר גרמני פריך ונקי עם מרירות מאוזנת.',
        'product.article.Superior': 'סטאוט אירי עשיר וחזק עם טעמי לתת עמוקים.',
				'Wine Fiuza Native Reserva 2018': 'יין פיוזה רזרבת 2018',
				'Wine Oceanius Produto De Portugal 2019': 'מוצר יין אושניוס מפורטוגל 2019',
				'product.article.oceaniusProdutoDePortugal2019': 'זהו יין נהדר, המשלב תווי פירות טריים ורכות מאפיינים של יינות פורטוגזים',
				productarticlfiuzaChardonnayArinto:
				'זהו יין שמנת עם דומיננטיות של שרדונטה ומניותיו של ארינטו. ',
				'product.article.fiuzaNativeReserva2018': 'זהו יין אלגנטי עם טעם עשיר, בו תווים של הקריקטורה שולטים, המשלימים את הרעננות המעודנת של ארינטו.',
				'Warning about alcohol': 'אלכוהול מזיק לבריאותך!',
				'product.article.portoCabracoRose': 'זהו פורט ורוד מרענן עם ניחוחות פירותיים, נפח הבקבוק 750 מ"ל.',
				'product.article.portoCabracoWhite': 'זהו יין פורט אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.portoCabracoRuby': 'זהו יין פורט אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				warning:
					'אזהרה: צריכת אלכוהול מופרזת עלולה להזיק לבריאותך. אנא שתה באחריות',
				'Learn More': 'קרא עוד',
				'Discover the Finest Alcoholic Beverages at R.I.L.L Collection':
					'גלו את המשקאות האלכוהוליים הטובים ביותר ב-R.I.L.L Collection',
				'Best Alcohol from all over the world':
					'האלכוהול הטוב ביותר מכל רחבי העולם',
				'Open Catalog': 'פתח קטלוג',
				Catalog: 'קטלוג',
				'Get In Touch': 'צור קשר',
				'We are in Facebook, Tiktok, & Instagram. You can also contact us via Email.':
					'אנחנו בפייסבוק, בטיקטוק ובאינסטגרם. ניתן גם ליצור איתנו קשר באמצעות דוא"ל.',
				'Page Not Found': 'Страница не найдена',
				'Go Back Home': 'הדף לא נמצא',
				'Contact Us': 'צור קשר',
				Contact: 'צור קשר',
				Reviews: 'הדעת',
				'Wine Fiuza Chardonnay Arinto Native Reserva 2017': 'יין פיוזה שרדונה ארינטו יליד רזרבה 2017 ',
				'Alcohol 🍾': 'אלכוהול 🍾',
				Insights: 'תובנות',
				'Popular product categories': 'קטגוריות מוצרים פופולריות',
				Permalinks: 'קישורים קבועים',
				Blog: 'בלוג',
				Search: 'לחפש',
				Communities: 'קהילות',
				Vodkino: 'וודקה בטעמים',
				'Our Socials and contacts.': 'הרשתות החברתיות ואנשי הקשר שלנו.',
				'Our Catalog': 'הקטלוג שלנו',
				'Import and marketing of quality products.':
					'יבוא ושיווק מוצרים איכותיים.',
				'Street 8 Azur': 'החצב 8 אזור',
				'Postal code 5802920, Israel': 'מיקוד 5802920, ישראל',
				'Phone ☎: 03-6542200 Mobile 📱: 052-4448940':
					'טלפון ☎: 03-6542200 נייד 📱: 052-4448940',
				'Email: rillcollection2023@gmail.com':
					'מייל: rillcollection2023@gmail.com',
				'Page Not Found': 'הדף לא נמצא',
				Home: 'בית',
				'Welcome!': 'ברוכים הבאים!',
				'Verify that you are legal age.': 'ודא שאתה בגיל החוקי',
				"I'm above 18": 'אני מעל 18',
				"I'm under 18": 'אני מתחת ל 18',
				'All Categories': 'כל הקטגוריות',
				'Warning: contains alcohol, it is recommended to avoid excessive drinking':
					'אזהרה: מכיל אלכוהול מומלץ להימנע משתיה מופרזת',
				'Warning! Excessive consumption of alcohol is life-threatening and harmful to health':
					'אזהרה! צריכה מופרזת של אלכוהול מסכנת חיים ומזיקה לבריאות',
				'Port wine': 'יַיִן פּוֹרט',
			},
		},
	},
	lng: 'he',
	fallbackLng: 'he',
	ns: ['translations'],
	defaultNS: 'translations',
	keySeparator: false,
	interpolation: {
		escapeValue: false,
		formatSeparator: ',',
	},
	react: {
		wait: true,
	},
})

const root = ReactDOM.createRoot(document.querySelector('#root'))

root.render(<App />)
