import i18n from 'i18next'
import ReactDOM from 'react-dom/client'
import { initReactI18next } from 'react-i18next'
import App from './App'
import './index.css'

const savedLanguage = localStorage.getItem('language') || 'עברית';

i18n.use(initReactI18next).init({
	resources: {
		English: {
			translations: {
				'We are on Facebook, Tiktok, & Instagram. You can also contact us via Email.': 'We are on Facebook, Tiktok, & Instagram. You can also contact us via Email.',
				Vodkino: 'Vodka Flavors',
				Port: 'Port 🍇',
				Arak: 'Arak 🌿',
				Beer: 'Beer 🍺',
				Vodka: 'Vodka ❄️',
				Liquor: 'Liquor 🥃',
				Brandy: 'Brandy ☀️',
				VilageWine: 'Village Wine 🍷',
				Gin: 'Gin 🍸',
				'Open Catalog': 'OPEN CATALOG',
				spirits: 'Vodka with flavors 🍒',
				'product.article.GINTraditional': 'This is Traditional Gin with a smooth taste.',
				'product.article.Beresheet.Cabernet.2021.wine': 'This is a rich red fromn Israel with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Beresheet.Reserve.2021.wine': 'This is a rich red wine from Israel with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.VodkaManhattanMelon': 'This is a premium vodka Manhattan from Israel with Melon flavor, 37.5% alcohol strength and 700ml volume.',
				'product.article.VodkaManhattanAsay': 'This is a premium vodka Manhattan from Israel with 37.5% alcohol strength and 700ml volume.',
				'product.article.VodkaManhattanPineapple': 'This is a premium vodka Manhattan from Israel with 37.5% alcohol strength and 700ml volume.',
				'product.article.BrandyMapleBrandyLouisXVDelicieuxBrand': 'This is a rich brandy with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.BrandyCherryBrandyLouisXVDelicieuxBrand': 'This is a rich brandy with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.BrandyHoneyBrandyLouisXVDelicieuxBrand': 'This is a rich brandy with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.BrandyAppleBrandyLouisXVDelicieuxBrand': 'This is a rich brandy with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.BrandyRoseBrandyLouisXVDelicieuxBrand': 'This is a rich brandy with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.Beresheet.VodkaImperial': 'This is a premium vodka from Israel with 37.5% alcohol strength and 700ml volume.',
				'product.article.GiladAppleVilageWine': 'This is an Israeli village wine GILAD with an apple flavor.',
				'product.article.GiladCherryVilageWine': 'This is an Israeli village wine GILAD with a cherry flavor.',
				'product.article.GiladRaspberryVilageWine': 'This is an Israeli village wine GILAD with a raspberry flavor.',
				'product.article.HarelBlueBerryVilageWine': 'This is an Israeli village wine Harel with a blueberry flavor.',
				'product.article.GILADLemonVilageWine': 'This is an Israeli village wine GILAD with a lemon flavor.',
				'product.article.HarelCurrantsVilageWine': 'This is an Israeli village wine Harel with a currant flavor.',
				'product.article.GILADOrange,': 'This is an Israeli village wine GILAD with an orange flavor.',
				'product.article.WineConvetoDaVilaRed,': 'This is a red wine with bright fruit notes, the bottle volume is 1 liter.',
				'product.article.WineConvetoDaVilaBranco2023,': 'This is a white wine with bright fruit notes, the bottle volume is 1 liter.',
				'product.article.CognacMaximeTrijolXOGrandeChampagne': 'This cognac has a rich aroma and deep flavor with notes of vanilla and oak.',
				'product.article.CognacMaximeTrijolVSOPGrandeChampagne': ' A completely unique cognac experience with vanilla and delicious spices with dried fruit on the initial aromas. Well-structured body with a light and elegant touch.',
				'product.article.MaximeTrijolCognacVSOP750ML': 'Maxime Trijol VSOP Superieur – amber colour with flashes of gold. A complex, mellow nose, a velvety balance on the palate with hits of dried fruit and hazelnut, backed by a rich and harmonious texture.',
				'product.article.MaximeTrijolCognacVS50ML': 'This drink is made according to centuries-old traditions using select ingredients. Each production stage is strictly controlled.',
				'product.article.MaximeTrijolCognacXO50ML': 'Cognac Maxime Trijol XO 50 ml',
				'product.article.MaximeTrijolCognacVSOP50ML': 'Cognac Maxime Trijol VSOP 50 ml',
				'product.article.WineFiuzaNativeReservaWhite2018,': 'Native range presents Portuguese varietals in a blend with the most well-known French grapes.',
				'product.article.MaximeTrijolCognacVSOP700ML': 'Cognac Maxime Trijol VSOP 700 ml',
				'product.article.BrandyLouisXVDelicieuxBrand': 'This is a rich brandy with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.WineEasyFritzDurelloGleraWhite': 'This is a white wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.WineVelasCorsariasWhite': 'This is a white wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.WineRosatoFrizzante': 'This is a fresh pink wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Beresheet.GalitosWhite': 'A clear visual, citrus color, with a greenish hue. The aroma is of tropical fruits and nuts. The flavor is smooth, balanced, showing ripe tropical fruit flavors with a fresh finish.',
				'product.article.Beresheet.GalitosRose': 'Bright, pink with slight orange gleams. Intense aroma of forest fruit. Well-balanced, young and excellent freshness, with a fruity persistence.',
				'product.article.Beresheet.GalitosTintoRegionalAlentejo': 'Ruby-coloured, with a young and red fruits aroma typical of the Castelão grapes. Fruity flavour with nice notes of strawberry, typical of the Aragonez variety, a fine and well-balanced freshness offered by Trincadeira.',
				'product.article.Beresheet.VodkaRusStandart200ml': 'Vodka Russian Standart 200 ml',
				'product.article.Beresheet.BrandyLouisXVFineOldBrand,wine': 'This is a rich brand with bright fruit notes, the bottle volume is 175 ml.',
				'product.article.Beresheet.BrandyLouisXVOrange,wine': 'This is a rich brand with bright fruit notes, the bottle volume is 700 ml.',
				'product.article.Beresheet.WineGrandNoirRose,wine': '	Pale pink. Intense aromas of raspberry, strawberry and redcurrant with a hint of pepper. Rich palette with refreshing bright red fruit and peppery character. Apparently dry, with attractive fruit-sweetness.',
				'product.article.Beresheet.WineGeorgianAlazaniValleyWhiteSemiSweetwine': 'This is a rich white wine from Georgia with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Beresheet.WineGeorgianAlazaniValleyRedSemiSweet,.2023.wine': 'This is a rich red wine from Georgia with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Beresheet.BeresheetReserveMerilotShraz.2023.wine': 'This is a rich red wine from Israel with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Beresheet.Port.2023.wine': 'This is a rich red from Israel with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Beresheet.Reserve.2023.wine': 'This is a rich red wine from Israel with bright fruit notes, the bottle volume is 750 ml.',
				'R.I.L.L Collection online storefront': 'R.I.L.L Collection online storefront',
				'You must be over 18 to access this site.': 'You must be over 18 to access this site.',
				'Access Denied': 'Access Denied',
				'product.article.Beresheet.Cabernet.2023.wine': 'This is a rich red wine from Israel with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.Albergaria.Limoncello.liqour': 'Limoncello is one of the most famous and consumed liqueurs in the world. ',
				'product.article.VodkaMoskva': 'Vodka Moskva is a premium vodka from Israel with 35% alcohol strength and 175ml volume.',
				'product.article.VodkaManhattan': 'Vodka Manhattan is a premium vodka from Israel with 37.5% alcohol strength and 700ml volume.',
				'product.article.VodkaIcePalace500ml': 'Vodka Ice Palace 500ml is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaPrimeBlanche': 'Vodka Prime Blanche is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaPrimeNoir': 'Vodka Prime Noir is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaIcePalace': 'Vodka Ice Palace is a premium vodka from Ukraine with 40% alcohol strength and 1L volume.',
				'product.article.VodkaNepoborna': 'Vodka Nepoborna is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.VodkaRusStandart.1l': 'Vodka Russian Standart is a premium vodka from Russia with 40% alcohol strength and 1L volume.',
				'product.article.CognacSikvaruli5': 'This is a premium cognac aged for 5 years with a deep, complex flavor.',
				'product.article.Cognac.Sikvaruli': 'This is a fine cognac with a rich aroma and smooth finish.',
				'product.article.Taller.Beer': 'This is a refreshing beer with a smooth taste.',
				'product.article.KrauzerBrau.Beer': 'This is a classic German Helles beer with a smooth and refreshing taste.',
				'product.article.Chernigivske': 'This is a clean and refreshing German pilsner beer with balanced bitterness.',
				'product.article.Superior.Beer': 'This is a rich and robust Irish stout with deep malt flavors.',
				'product.article.EichbaumPilsenerBeer': 'This is a clean and refreshing German pilsner beer with balanced bitterness.',
				'product.article.EichbaumHellBeer': 'This is a classic German Helles beer',
				'product.article.arakLemon': 'This is a traditional arak with a refreshing lemon flavor, the bottle volume is 750 ml.',
				'product.article.arakOrange': 'This is a traditional arak with a refreshing orange flavor, the bottle volume is 750 ml.',
				'product.article.vodkinaPeach': 'This is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.vodkinaOrange': 'This is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.vodkinaLemon': 'This is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.vodkinaYellow': 'This is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.vodkinaMango': 'This is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.arakOrange': 'This is a traditional arak with a refreshing orange flavor, the bottle volume is 750 ml.',
				'product.article.maximeTrijolCognac3L': 'Cognac Maxime Trijol 3L',
				'product.article.summerMerlotAllSeasonsCollection2020': 'This is a rich red wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.spainVelasCorsarias': 'This is a red wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.biancoCChardonnayAllSeasonsCollection2020': 'This is a creamy wine, dominated by Chardonnay and a fraction of Arinto.',
				'product.article.montesCarlosDOCAlentejoTinto2016': 'This is a rich red wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.fiuzaMerilot2015': 'This is a rich red wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.adegaDeBorba': 'This is a rich red wine with bright fruit notes, the bottle volume is 750 ml.',
				'product.article.fiuzaCabernet.Sauvignon' : 'This is a rich red wine with a full body and a long finish, the bottle volume is 750 ml.', 
				'product.article.oceaniusProdutoDePortugal2019': 'This is an exquisite wine, combining fresh fruit notes and softness characteristic of Portuguese wines',
				'product.article.fiuzaNativeReserva2018': 'This is an elegant wine with a rich taste, where the notes of the cartoon dominate, complemented by the exquisite freshness of Arinto.',
				'product.article.maximeTrijolCognacSmall': 'Cognac Maxime Trijol Small',
				'product.article.maximeTrijolCognacVsop': 'Cognac Maxime Trijol Vsop',
				'product.article.maximeTrijolCognacEiffelTower': 'Cognac Maxime Trijol Eiffel Tower',
				'product.article.VodkaRusStandart': 'Vodka Russian Standart is a premium vodka from Russia with 40% alcohol strength and 1L volume.',
				'product.article.VodkaMoskva': 'Vodka Moskva is a premium vodka from Israel with 35% alcohol strength and 175ml volume.',	
				'product.article.VodkaManhattan': 'Vodka Manhattan is a premium vodka from Israel with 37.5% alcohol strength and 700ml volume.',
				'product.article.VodkaIcePalace500': 'Vodka Ice Palace 500ml is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaPrimeBlanche': 'Vodka Prime Blanche is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaPrimeNoir': 'Vodka Prime Noir is a premium vodka from Ukraine with 40% alcohol strength and 500ml volume.',
				'product.article.VodkaIcePalace': 'Vodka Ice Palace is a premium vodka from Ukraine with 40% alcohol strength and 1L volume.',
				'product.article.VodkaNepoborna': 'Vodka Nepoborna is a premium vodka from Ukraine with 40% alcohol strength and 700ml volume.',
				'product.article.portoCabracoRuby': 'It is a rich red port wine with bright fruit notes, the bottle volume is 750 ml.',
                'product.article.Taller': 'A refreshing beer with a smooth taste.',
                'product.article.CognacSikvaruli': 'A fine cognac with a rich aroma and smooth finish.',
                'product.article.CognacSikvaruli5': 'A premium cognac aged for 5 years with a deep, complex flavor.',
                'product.article.VodkaRussianStandart1894': 'A classic Russian vodka with a clean, crisp taste.',
				'product.article.EichbaumHell': 'A classic German Helles beer with a smooth and refreshing taste.',
        'product.article.EichbaumPilsener': 'A crisp and clean German Pilsener with a balanced bitterness.',
        'product.article.Superior': 'A rich and robust Irish stout with deep malt flavors.',
				'product.article.oceaniusProdutoDePortugal2019': 'This is an exquisite wine, combining fresh fruit notes and softness characteristic of Portuguese wines',
				'Warning about alcohol': 'Alcohol is harmful to your health!',
				Wine: 'Wine 🍷',
				Cognac: 'Cognac 🥂',
				'product.article.portoCabracoRose': 'It is a refreshing pink port wine with fruity aromas and the bottle volume is 750 ml.',
				'product.article.portoCabracoWhite': 'It is a white port wine with a mild and sweet flavor and the bottle volume is 750 ml.',
				productarticlfiuzaChardonnayArinto:
					'This creamy wine, dominated by Chardonnay and a fraction of Arinto.',
					'product.article.fiuzaNativeReserva2018': 'This is an elegant wine with a rich taste, where the notes of the cartoon dominate, complemented by the exquisite freshness of Arinto.',
				warning:
					'Warning: Excessive alcohol consumption can be harmful to your health. Please drink responsibly.',
					'product.article.portoCabracoRuby': 'It is a rich red port wine with bright fruit notes, the bottle volume is 750 ml.'
			},
		},
		Русский: {
			translations: {
				'Gin experience traditional Premium': 'Джин experience traditional Premium',
				'Wine Beresheet Cabernet Sauvignon 2021': 'Вино Beresheet Cabernet Sauvignon 2021',
				'Wine Beresheet Reserve 2021': 'Вино Beresheet Reserve 2021',
				'Vodka Manhattan Melon': 'Водка Манхэттен Дыня',
				'Vodka Manhattan Asay': 'Водка Манхэттен Асай',
				'Vodka Manhattan Pineapple': 'Водка Манхэттен Ананас',
				'Brandy Louis XV Delicieux Brand Maple': 'Бренди Louis XV Delicieux Brand Maple',
				'product.title.CherryBrandyLouisXVDelicieuxBrand,': 'Бренди Louis XV Delicieux Brand Cherry',
				'Brandy Louis XV Delicieux Brand Honey': 'Бренди Louis XV Delicieux Brand Honey',
				'Brandy Louis XV Delicieux Brand Apple': 'Бренди Louis XV Delicieux Brand Apple',
				'Brandy Louis XV Delicieux Brand Rose': 'Бренди Louis XV Delicieux Brand Rose',
				'Vodka Imperial 700ml': 'Водка Imperial 700 мл',
				'Vilage Wine GILAD Apple taste': 'Деревенское вино GILAD с яблочным вкусом',
				'Vilage Wine GILAD Cherry taste': 'Деревенское вино GILAD с вишневым вкусом',
				'Vilage Wine GILAD Raspberry taste': 'Деревенское вино GILAD с малиновым вкусом',
				'Vilage Wine Harel Blueberry taste': 'Деревенское вино Harel с вкусом черники',
				'Vilage Wine GILAD Lemon taste': 'Деревенское вино GILAD с лимонным вкусом',
				'Vilage Wine Harel Currants': 'Деревенское вино Harel с вкусом смородины',
				'Vilage Wine GILAD Orange Apricot taste': 'Деревенское вино GILAD с апельсиново-абрикосовым вкусом',
				'Vilage Wine GILAD Orange taste': 'Деревенское вино GILAD с апельсиновым вкусом',
				'Wine Convento Da Vila Red': 'Вино Convento Da Vila Red',
				'Wine Convento Da Vila Branco 2023': 'Вино Convento Da Vila Branco 2023',
				'Cognac Maxime Trijol XO Grande Champagne': 'Коньяк Maxime Trijol XO Grande Champagne',
				'Cognac Maxime Trijol V.S.O.P Grande Champagne': 'Коньяк Maxime Trijol V.S.O.P Grande Champagne',
				'Cognac Maxime Trijol V.S.O.P 750ml': 'Коньяк Maxime Trijol V.S.O.P 750 мл',
				'Cognac Maxime Trijol VS 50ml': 'Коньяк Maxime Trijol VS 50 мл',
				'Cognac Maxime Trijol V.S.O.P 50ml': 'Коньяк Maxime Trijol V.S.O.P 50 мл',
				'Cognac Maxime Trijol XO 50ml': 'Коньяк Maxime Trijol XO 50 мл',
				'Wine Fiuza Native Reserva White 2018': 'Вино Fiuza Native Reserva White 2018',
				'Cognac Maxime Trijol V.S.O.P 700ml': ' Коньяк Maxime Trijol V.S.O.P 700 мл',
				'Brandy Louis XV Delicieux Brand': 'Бренди Louis XV Delicieux Brand',
				'Wine Easy Fritz Durello-Glera': 'Вино Easy Fritz Durello-Glera',
				'Wine Velas Corsarias': 'Вино Velas Corsarias',
				'Wine ROSATO FRIZZANTE - EASY FRITZ': 'Вино ROSATO FRIZZANTE - EASY FRITZ',
				'Wine Galitos White': 'Вино Galitos White',
				'Wine Galitos Rose': 'Вино Galitos Rose',
				'Wine Galitos Tinto Regional Alentejo': 'Вино Galitos Tinto Regional Alentejo',
				'Vodka Russian Standart 1894 200ml': 'Водка Russian Standart 1894 200 мл',
				'Brandy Louis XV Orange': 'Бренди Louis XV Orange',
				'Wine Le Grand Noir Rose': 'Вино Le Grand Noir Rose',
				'Wine Georgian Alazani Valley White Semi-Sweet': 'Вино грузинское Алазанская долина белое полусладкое',
				'Wine Georgian Alazani Valley Red Semi-Sweet': 'Вино грузинское Алазанская долина красное полусладкое',
				'Wine Beresheet Reserve Merilot Shraz 2023': 'Вино Beresheet Reserve Merilot Shraz 2023',
				'Port Beresheet  2023': 'Портвейн Beresheet 2023',
				'Wine Beresheet Reserve Cabernet Sauvignon 2023': 'Вино Beresheet Reserve Cabernet Sauvignon 2023',
				'Vilage Wine GILAD Orange Apricot taste': 'Деревенское вино GILAD с апельсиново-абрикосовым вкусом',
				Insights: 'Наше онлайн пространство',
				Description: 'Описание',
				HOME: 'ГЛАВНАЯ',
				CATALOG: 'КАТАЛОГ',
				CONTACT: 'КОНТАКТЫ',
				NEXT: 'ВПЕРЕД',
				PREVIOUS: 'НАЗАД',
				'Vodka Moskva': 'Водка Moskva',
				'product.article.GINTraditional': 'Это традиционный джин с гладким вкусом.',
				'product.article.Beresheet.Cabernet.2021.wine': 'Это богатое красное вино из Израиля с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.VodkaManhattanMelon': 'Это премиальная водка Manhattan из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.BrandyCherryBrandyLouisXVDelicieuxBrand': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.BrandyAppleBrandyLouisXVDelicieuxBrand': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.Beresheet.VodkaImperial': 'Это премиальная водка из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.GILADApricot,': 'Это израильское деревенское вино GILAD c абрикосовым фкусом.',
				'product.article.MaximeTrijolCognacXO50ML': 'Коньяк Maxime Trijol XO 50 мл',
				'product.article.BrandyLouisXVDelicieuxBrand': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.WineEasyFritzDurelloGleraWhite': 'Это белое вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.Beresheet.GalitosWhite': 'Прозрачный визуальный, цитрусовый цвет, с зеленоватым оттенком. Аромат тропических фруктов и орехов. Вкус гладкий, сбалансированный, показывает спелые вкусы тропических фруктов с свежим послевкусием.',
				'product.article.Beresheet.GalitosRose': 'Яркий, розовый с легкими оранжевыми отблесками. Интенсивный аромат лесных фруктов. Хорошо сбалансированный, молодой и отличной свежести, с фруктовой стойкостью.',
				'product.article.Beresheet.BrandyLouisXVOrange,wine': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.Beresheet.WineGrandNoirRose,wine': 'Бледно-розовый. Интенсивные ароматы малины, клубники и красной смородины с намеком на перец. Богатая палитра с освежающими яркими красными фруктами и перчинкой. По-видимому сухое, с привлекательной фруктовой сладостью.',
				'product.article.Beresheet.Cabernet.2023.wine': 'Это богатое красное вино из Израиля с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'Albergaria Limoncello Liquor 700ml': 'Ликер Albergaria Limoncello 700мл',
				'product.article.Albergaria.Limoncello.liqour': 'Лимончелло - один из самых известных и потребляемых ликеров в мире.',
				'Beer Eichbaum Hefeweizen Hell 500ml': 'Пиво Eichbaum Hefeweizen Hell 500мл',
				'Beer Eichbaum Helles Large Hell 500ml': 'Пиво Eichbaum Helles Large Hell 500мл',
				'Beer Eichbaum Pilsener 500ml': 'Пиво Eichbaum Pilsener 500мл',
				'Beer Superior Stout 500ml': 'Пиво Superior Stout 500мл',
				'Beer Chernigivske': 'Пиво Черниговское',
				'product.article.Chernigivske.Beer': 'Это чистое и освежающее украинское пиво с сбалансированной горечью.',
				'Beer Krauzer Brau': 'Пиво Krauzer Brau',
				'Beer Taller': 'Пиво Taller',
				'Cognac Sikvaruli 3': 'Коньяк Sikvaruli 3',
				'Cognac Sikvaruli 5': 'Коньяк Sikvaruli 5',
				'Vodka Russian Standart 1894 1l': 'Водка Русский Стандарт 1894 1 литр',
				'Vodka Nepoborna 700ml': 'Водка Nepoborna 700 мл',
				'Vodka Ice Palace 1l': 'Водка Ice Palace 1 литр',
				'Vodka Prime Noir': 'Водка Prime Noir 500 мл',
				'Vodka Prime Blanche': 'Водка Prime Blanche 500 мл',
				'Vodka Ice Palace 500ml': 'Водка Ice Palace 500 мл',
				'Vodka Manhattan': 'Водка Manhattan',
				'R.I.L.L Collection online storefront': 'Интернет-магазин R.I.L.L Collection',
				'ALL PRODUCTS': 'ВСЕ ПРОДУКТЫ',
				'More Details': 'Подробнее',
				'Bottle Volume': 'Объем бутылки',
				Origin: 'Страна',
				'Alcohol Strength': 'Содержание алкоголя',
				'Alcohol 🍾': 'Алкоголь 🍾',
				Portugal: 'Португалия',
				'Show All Results': 'ВСЕ РЕЗУЛЬТАТЫ',
				spirits: 'Водка со вкусами 🍒',
				Search: 'Поиск',
				Port: 'Портвейн 🍇',
				VilageWine: 'Деревенское вино 🍷',
				Liquor: 'Ликер 🥃',
				'product.article.Beresheet.Reserve.2021.wine': 'Это богатое красное вино из Израиля с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.VodkaManhattanAsay': 'Это премиальная водка Manhattan из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.VodkaManhattanPineapple': 'Это премиальная водка Manhattan из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.BrandyMapleBrandyLouisXVDelicieuxBrand': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.BrandyHoneyBrandyLouisXVDelicieuxBrand': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.BrandyRoseBrandyLouisXVDelicieuxBrand': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 700 мл.',
				'product.article.GiladAppleVilageWine': 'Это израильское деревенское вино GILAD с яблочным вкусом.',
				'product.article.GiladCherryVilageWine': 'Это израильское деревенское вино GILAD с вишневым вкусом.',
				'product.article.GiladRaspberryVilageWine': 'Это израильское деревенское вино GILAD с малиновым вкусом.',
				'product.article.HarelBlueBerryVilageWine': 'Это израильское деревенское вино Harel с вкусом черники.',
				'product.article.GILADLemonVilageWine': 'Это израильское деревенское вино GILAD с лимонным вкусом.',
				'product.article.HarelCurrantsVilageWine': 'Это израильское деревенское вино Harel с вкусом смородины.',
				'product.article.GILADOrange,':'Это израильское деревенское вино GILAD c апельсиновым фкусом.',
				'product.article.WineConvetoDaVilaRed,': 'Это красное вино с яркими фруктовыми нотами, объем бутылки составляет 1 литр.',
				'product.article.WineConvetoDaVilaBranco2023,': 'Это белое вино с яркими фруктовыми нотами, объем бутылки составляет 1 литр.',
				'product.article.CognacMaximeTrijolXOGrandeChampagne': 'Этот коньяк обладает насыщенным ароматом и глубоким вкусом с нотками ванили и дуба.',
				'product.article.CognacMaximeTrijolVSOPGrandeChampagne': 'Полностью уникальный опыт коньяка с ванилью и вкусными специями с сухофруктами на начальных ароматах. Хорошо структурированное тело с легким и элегантным прикосновением.',
				'product.article.MaximeTrijolCognacVSOP750ML': 'Коньяк Maxime Trijol VSOP 750 мл',
				'product.article.MaximeTrijolCognacVS50ML': 'Напиток изготовлен согласно вековым традициям с использованием отборных ингредиентов. Каждый производственный этап строго контролируется.',
				'product.article.MaximeTrijolCognacVSOP50ML': 'Коньяк Maxime Trijol VSOP 50 мл',
				'product.article.WineFiuzaNativeReservaWhite2018,': 'виноградные сорта Португалии в смеси с наиболее известными французскими виноградами.',
				'product.article.MaximeTrijolCognacVSOP700ML': 'Коньяк Maxime Trijol VSOP 700 мл',
				'product.article.WineVelasCorsariasWhite': 'Это белое вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.WineRosatoFrizzante': 'Это свежее розовое вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.Beresheet.GalitosTintoRegionalAlentejo': 'Рубинового цвета, с молодым и ароматом красных фруктов, характерным для винограда Кастелан. Фруктовый вкус с приятными нотами клубники, характерными для сорта Арагонез, тонкой и хорошо сбалансированной свежестью, предлагаемой Тринкадейра.',
				'product.article.Beresheet.VodkaRusStandart200ml': 'Водка Русский Стандарт 200 мл',
				'product.article.Beresheet.BrandyLouisXVFineOldBrand,wine': 'Это богатый бренди с яркими фруктовыми нотами, объем бутылки составляет 175 мл.',
				'product.article.Beresheet.WineGeorgianAlazaniValleyWhiteSemiSweetwine': 'Это богатое белое вино из Грузии с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.Beresheet.WineGeorgianAlazaniValleyRedSemiSweet,.2023.wine': 'Это богатое красное вино из Грузии с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.Beresheet.BeresheetReserveMerilotShraz.2023.wine': 'Это богатое красное вино из Израиля с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.Beresheet.Reserve.2023.wine': 'Это богатое красное вино из Израиля с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'You must be over 18 to access this site.': 'Вам должно быть больше 18 лет, чтобы получить доступ к этому сайту.',
				'Access Denied': 'Вход запрещен',
				'product.article.Beresheet.Port.2023.wine': 'Это богатое красное вино из Израиля с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.VodkaMoskva': 'Водка Москва - это премиальная водка из Израиля с крепостью 35% и объемом 175 мл.',
				'product.article.VodkaManhattan': 'Водка Манхэттен - это премиальная водка из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.VodkaManhattan': 'Водка Манхэттен - это премиальная водка из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.VodkaIcePalace500ml': 'Водка Айс Палас 500 мл - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaPrimeBlanche': 'Водка Прайм Бланш - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaPrimeNoir': 'Водка Прайм Нуар - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaIcePalace': 'Водка Айс Палас - это премиальная водка из Украины с крепостью 40% и объемом 1 литр.',
				'product.article.VodkaNepoborna': 'Водка Непоборна - это премиальная водка из Украины с крепостью 40% и объемом 700 мл.',
				'product.article.VodkaRusStandart.1l': 'Водка Русский Стандарт - это премиальная водка из России с крепостью 40% и объемом 1 литр.',
				'product.article.CognacSikvaruli5': 'Это премиальный коньяк с богатым ароматом и гладким послевкусием.',
				'product.article.Cognac.Sikvaruli': 'Это изысканный коньяк с богатым ароматом и гладким послевкусием.',
				'product.article.Taller.Beer': 'Это освежающее пиво с гладким вкусом.',
				'product.article.KrauzerBrau.Beer': 'Это классическое немецкое светлое пиво с мягким и освежающим вкусом.',
				'product.article.Chernigivske': 'Это чистое и освежающее немецкое пиво пильзнер с сбалансированной горечью.',
				'product.article.Superior.Beer': 'Это богатый и крепкий ирландский стаут с глубокими солодовыми нотами.',
				'product.article.EichbaumPilsenerBeer': 'Это чистое и освежающее немецкое пиво пильзнер с сбалансированной горечью.',
				'product.article.EichbaumHellBeer': 'Это классическое немецкое светлое пиво с мягким и освежающим вкусом.',
				'product.article.arakLemon': 'Это традиционный арак с освежающим лимонным вкусом, объем бутылки 750 мл.',
				'product.article.arakOrange': 'Это традиционный арак с освежающим апельсиновым вкусом, объем бутылки 750 мл.',
				'product.article.vodkinaPeach': 'Это премиальная водка из Украины с крепостью 40% и объемом 700 мл.',
				'product.article.vodkinaOrange': 'Это премиальная водка из Украины с крепостью 40% и объемом 700 мл.',
				'product.article.vodkinaLemon': 'Это премиальная водка из Украины с крепостью 40% и объемом 700 мл.',
				'product.article.vodkinaYellow': 'Это премиальная водка из Украины с крепостью 40% и объемом 700 мл.',
				'product.article.vodkinaMango': 'Это премиальная водка из Украины с крепостью 40% и объемом 700 мл.',
				'product.article.arakOrange': 'Это традиционный арак с освежающим апельсиновым вкусом, объем бутылки 750 мл.',
				'product.article.maximeTrijolCognac3L': 'Коньяк Максим Трижоль 3 литра',
				'product.article.summerMerlotAllSeasonsCollection2020': 'Это богатое красное вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.spainVelasCorsarias': 'Это красное вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.biancoCChardonnayAllSeasonsCollection2020': 'Это кремовое вино, доминирующее Шардоне и доля Аринто.',
				'product.article.montesCarlosDOCAlentejoTinto2016': 'Это богатое красное вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.fiuzaMerilot2015': 'Это богатое красное вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.adegaDeBorba': 'Это богатое красное вино с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'product.article.fiuzaCabernet.Sauvignon' : 'Это богатое красное вино с насыщенным вкусом и длительным послевкусием, объем бутылки 750 мл.',
				'product.article.oceaniusProdutoDePortugal2019': 'Это изысканное вино, сочетающее в себе свежие фруктовые ноты и мягкость, характерную для португальских вин',
				'product.article.fiuzaNativeReserva2018': 'Это элегантное вино с насыщенным вкусом, где доминируют ноты Шардоне, дополненные изысканной свежестью Аринто.',
				'product.article.maximeTrijolCognacSmall': 'Коньяк Максим Трижоль Маленький',
				'product.article.maximeTrijolCognacVsop': 'Коньяк Максим Трижоль Всоп',
				'product.article.maximeTrijolCognacEiffelTower': 'Коньяк Максим Трижоль Эйфелева башня',
				'product.article.VodkaRusStandart': 'Водка Русский Стандарт - это премиальная водка из России с крепостью 40% и объемом 1 литр.',
				'product.article.VodkaMoskva': 'Водка Москва - это премиальная водка из Израиля с крепостью 35% и объемом 175 мл.',
				'product.article.VodkaManhattan': 'Водка Манхэттен - это премиальная водка из Израиля с крепостью 37.5% и объемом 700 мл.',
				'product.article.VodkaIcePalace500': 'Водка Айс Палас 500 мл - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaPrimeBlanche': 'Водка Прайм Бланш - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaPrimeNoir': 'Водка Прайм Нуар - это премиальная водка из Украины с крепостью 40% и объемом 500 мл.',
				'product.article.VodkaIcePalace': 'Водка Айс Палас - это премиальная водка из Украины с крепостью 40% и объемом 1 литр.',
				'product.article.VodkaNepoborna': 'Водка Непоборна - это премиальная водка из Украины с крепостью 40% и объемом 700 мл',
				'product.article.EichbaumHell': 'Классическое немецкое светлое пиво с мягким и освежающим вкусом.',
        'product.article.EichbaumPilsener': 'Чистый и освежающий немецкий пилснер с сбалансированной горечью.',
        'product.article.Superior': 'Богатый и крепкий ирландский стаут с глубокими солодовыми нотами.',
				'product.article.oceaniusProdutoDePortugal2019': 'Это изысканное вино, сочетающее в себе свежие фруктовые ноты и мягкость, характерную для португальских вин',
				'product.article.fiuzaNativeReserva2018': 'Это элегантное вино с насыщенным вкусом, где доминируют ноты Шардоне, дополненные изысканной свежестью Аринто.',
				'Warning about alcohol': 'Алкоголь вреден для вашего здоровья!',
				'Wine Fiuza Chardonnay Arinto Native Reserva 2017': 'Вино Fiuza Chardonnay Arinto Native Reserva 2017',
				'productdetailsfiuzaChardonnayArinto': 'dda',
				'Port wine Cabraco Ruby': 'Портвейн Cabraco Ruby',
				'Port wine Cabraco White': 'Портвейн Cabraco White',
				'Port wine Cabraco Rose': 'Портвейн Cabraco Rose',
				'Cognac Maxime Trijol': 'Коньяк Maxime Trijol',
				'Cognac Maxime Trijol Vsop': 'Коньяк Maxime Trijol Vsop',
				'Cognac Maxime Trijol Small': 'Коньяк Maxime Trijol Small',
				'Wine Fiuza Native Reserva 2018': 'Вино Fiuza Native Reserva 2018',
				'Wine Oceanius Produto De Portugal 2019':
					'Вино Oceanius Produto De Portugal 2019',
				'Wine Fiuza Cabernet Sauvignon': 'Вино Fiuza Cabernet Sauvignon',
				'Wine Adega De Borba': 'Вино Adega De Borba',
				'Wine Fiuza Merilot 2015': 'Вино Fiuza Merilot 2015',
				'Wine Montes Carlos DOCA lentejo Tinto2016':
					'Вино Montes Carlos DOCA lentejo Tinto2016',
				'Wine Bianco Chardonnay AllSeasons Collection 2020':
					'Вино Bianco Chardonnay AllSeasons Collection 2020',
				'Wine Spain Velas Corsarias': 'Вино Spain Velas Corsarias',
				'Wine Summer Merlot AllSeasons Collection 2020':
					'Вино Summer Merlot AllSeasons Collection 2020',
				'Cognac Maxime Trijol 3L': 'Коньяк Maxime Trijol 3L',

				'Learn More': 'Узнать больше',
				Search: 'Поиск',
				'Cognac Maxime Trijol Eiffel Tower': 'Коньяк Maxime Trijol Eiffel Tower',
				'Discover the Finest Alcoholic Beverages at R.I.L.L Collection':
					'Откройте для себя лучшие алкогольные напитки в R.I.L.L Collection',
				'Best Alcohol from all over the world': 'Лучший алкоголь со всего мира',
				'Open Catalog': 'ВЕСЬ КАТАЛОГ',
				Catalog: 'Каталог',
				'Get In Touch': 'Свяжитесь с нами',
				'We are in Facebook, Tiktok, & Instagram. You can also contact us via Email.':
					'Мы есть в Facebook, Tiktok и Instagram. Вы также можете связаться с нами по электронной почте.',
				'Page Not Found': 'Страница не найдена',
				'Go Back Home': 'Вернутся назад',
				'Contact Us': 'Свяжитесь с нами',
				Contact: 'Контакты',
				Reviews: 'Отзывы',
				Permalinks: 'Постоянные ссылки',
				Blog: 'Блог',
				Beer: 'Пиво 🍺',
				Brandy: 'Бренди ☀️',
				Vodka: 'Водка ❄️',
				'Phone number copied!': 'Номер телефона скопирован!',
				Liquor: 'Ликер 🥃',
				Gin: 'Джин 🍸',
				'Copy phone number': 'Скопировать номер телефона',
				'Port wine': 'Портвейн',
				Wine: 'Вино 🍷',
				Arak: 'Арак 🌿',
				'product.article.portoCabracoRose': 'Это освежающий розовый портвейн с фруктовыми ароматами, объем бутылки составляет 750 мл.',
				'product.article.portoCabracoWhite': 'Это белый портвейн с мягким и сладким вкусом, объем бутылки составляет 750 мл.',
				warning:
					'Внимание: Чрезмерное употребление алкоголя вредит вашему здоровью.',
				Cognac: 'Коньяк 🥂',
				'Popular product categories': 'Популярные категории товаров',
				Communities: 'Сообщество',
				'product.article.portoCabracoRuby': 'Это насыщенный красный портвейн с яркими фруктовыми нотами, объем бутылки составляет 750 мл.',
				'Our Socials and contacts.': 'Наши социальные сети и контакты.',
				'Import and marketing of quality products.':
					'Импорт и реализация качественной продукции.',
				'Street 8 Azur': 'Улица 8 Азур',
				'Postal code 5802920, Israel': 'Почтовый индекс 5802920, Израиль',
				'Phone ☎: 03-6542200 Mobile 📱: 052-4448940':
					'Телефон ☎: 03-6542200 Мобильный 📱: 052-4448940',
				'Email: rillcollection2023@gmail.com':
					'Электронная почта: rillcollection2023@gmail.com',
				Home: 'Главная',
				'Welcome!': 'Добро пожаловать!',
				'Verify that you are legal age.':
					'Убедитесь, что вы достигли совершеннолетия.',
				"I'm above 18": 'Мне больше 18',
				"I'm under 18": 'Мне меньше 18',
				'All Categories': 'Все Категории',
				arak: 'Арак',
				'We are on Facebook, Tiktok, & Instagram. You can also contact us via Email.': 'Мы есть в Facebook, Tiktok и Instagram. Вы также можете связаться с нами по электронной почте.',
				'Warning: contains alcohol, it is recommended to avoid excessive drinking':
					'Внимание: содержит алкоголь, рекомендуется избегать чрезмерного употребления.',
				'Warning! Excessive consumption of alcohol is life-threatening and harmful to health':
					'Предупреждение! Чрезмерное употребление алкоголя опасно для жизни и вредно для здоровья',
				wine: 'Вино',
				portWine: 'Портвейн',
				producttitlefiuzaChardonnayArinto: 'Fiuza Chardonnay Arinto',
				cognac: 'Коньяк',
				productarticlfiuzaChardonnayArinto:
					'Это сливочное вино с преобладанием Шардоне и долей Аринто. ',
			},
		},
		עברית: {
			translations: {
				'Gin experience traditional Premium': 'ג\'ין חווית פרימיום מסורתי',
				'Wine Beresheet Cabernet Sauvignon 2021': 'יין בראשית קברנה סוביניון 2021',
				'Wine Beresheet Reserve 2021': 'יין בראשית ריזרב 2021',
				'Vodka Manhattan Melon': 'וודקה מנהטן מלון',
				'Vodka Manhattan Asay': 'וודקה מנהטן אסי',
				'Vodka Manhattan Pineapple': 'וודקה מנהטן אננס',
				'Brandy Louis XV Delicieux Brand Maple': 'ברנדי לואיס החמישי דליסיו ברנד מייפל',
				'product.title.CherryBrandyLouisXVDelicieuxBrand,': 'ברנדי דובדבן לואיס החמישי דליסיו ברנד',
				'Brandy Louis XV Delicieux Brand Honey': 'ברנדי לואיס החמישי דליסיו ברנד דבש',
				'Brandy Louis XV Delicieux Brand Apple': 'ברנדי לואיס החמישי דליסיו ברנד תפוח',
				'Brandy Louis XV Delicieux Brand Rose': 'ברנדי לואיס החמישי דליסיו ברנד רוזה',
				'Vodka Imperial 700ml': 'וודקה אימפריאל 700 מ"ל',
				'Vilage Wine GILAD Apple taste': 'שיכר גלעד | תפוח',
				'Vilage Wine GILAD Cherry taste': 'שיכר גלעד | דובדבן',
				'Vilage Wine GILAD Raspberry taste': 'שיכר גלעד | פטל',
				'Vilage Wine Harel Blueberry taste': 'שיכר דרים | חרמון תות כחול',
				'Vilage Wine GILAD Lemon taste': 'שיכר גלעד | לימון',
				'Vilage Wine Harel Currants': 'שיכר דרים | חרמון ענבים',
				'Vilage Wine GILAD Orange Apricot taste': 'גילעד | שיכר יין אפרסקים',
				'Vilage Wine GILAD Orange taste': 'שיכר הדרים | GILAD',
				'Wine Convento Da Vila Red': 'יין קונוונטו דה וילה אדום',
				'Wine Convento Da Vila Branco 2023': 'יין קונוונטו דה וילה בלאנקו 2023',
				'Cognac Maxime Trijol XO Grande Champagne': 'קוניאק מקסים טריג\'ול XO גרנד שמפניה',
				'Cognac Maxime Trijol V.S.O.P Grande Champagne': 'קוניאק מקסים טריג\'ול V.S.O.P גרנד שמפניה',
				'Cognac Maxime Trijol V.S.O.P 750ml': 'קוניאק מקסים טריג\'ול V.S.O.P 750 מ"ל',
				'Cognac Maxime Trijol VS 50ml': 'קוניאק מקסים טריג\'ול V.S 50 מ"ל',
				'Cognac Maxime Trijol V.S.O.P 50ml': 'קוניאק מקסים טריג\'ול V.S.O.P 50 מ"ל',
				'Cognac Maxime Trijol XO 50ml': 'קוניאק מקסים טריג\'ול XO 50 מ"ל',
				'Wine Fiuza Native Reserva White 2018': 'יין פיוזה נייטיב רזרבה לבן 2018',
				'Cognac Maxime Trijol V.S.O.P 700ml': 'קוניאק מקסים טריג\'ול V.S.O.P 700 מ"ל',
				'Brandy Louis XV Delicieux Brand': 'ברנדי לואיס החמישי דליסיו ברנד',
				'Wine Easy Fritz Durello-Glera': 'יין איזי פריץ דורלו-גלרה',
				'Wine Velas Corsarias': 'יין ולאס קורסאריאס',
				'Wine ROSATO FRIZZANTE - EASY FRITZ': 'יין רוזה פריזנטה - איזי פריץ',
				'Wine Galitos White': 'יין גאליטוס לבן',
				'Wine Galitos Rose': 'יין גאליטוס רוזה',
				'Wine Galitos Tinto Regional Alentejo': 'יין גאליטוס טינטו רגיונל אלנטג\'ו',
				'Vodka Russian Standart 1894 200ml': 'וודקה רוסית סטנדרט 1894 200 מ"ל',
				'Brandy Louis XV Orange': 'ברנדי לואיס החמישי תפוז',
				'Wine Le Grand Noir Rose': 'יין לה גראן נואר רוזה',
				'Wine Georgian Alazani Valley White Semi-Sweet': 'יין גאורגי עמק אלזני לבן חצי מתוק',
				'Wine Georgian Alazani Valley Red Semi-Sweet': 'יין גאורגי עמק אלזני אדום חצי מתוק',
				'Wine Beresheet Reserve Merilot Shraz 2023': 'בֶּרֶשִׁית רֶזֶרְבֵּה מֶרִילוֹט שִׁרָז 2023',
				'Port Beresheet  2023': 'בֶּרֶשִׁית פּוֹרט 2023',
				'Wine Beresheet Reserve Cabernet Sauvignon 2023': 'בֶּרֶשִׁית רֶזֶרְבֵּה 2023',
				Beer: 'בִּירָה 🍺',
				Vodka: 'ווֹדקָה ❄️',
				Wine: 'יַיִן 🍷',
				Brandy: 'בְּרַנְדִי ☀️',
				wine: 'יַיִן 🍷',
				Arak: 'ערק 🌿',
				Gin: 'ג\'ין 🍸',
				VilageWine: 'יין כפרי 🍇',
				spirits: 'וודקה עם טעמים 🍒',
				Cognac: 'קוניאק 🥂',
				Port: 'יַיִן פּוֹרט 🍇',
				HOME: 'בַּיִת',
				CATALOG: 'קָטָלוֹג',
				CONTACT: 'צור קשר',
				NEXT: 'הַבָּא',
				PREVIOUS: 'הַקוֹדֵם',
				'product.article.GINTraditional': 'ג\'ין מסורתי',
				'product.article.Beresheet.Cabernet.2021.wine': 'יין בראשית קברנה 2021',
				'product.article.Beresheet.Reserve.2021.wine': 'יין בראשית ריזרב 2021',
				'product.article.VodkaManhattanMelon': 'וודקה מנהטן מלון',
				'product.article.VodkaManhattanAsay': 'וודקה מנהטן אסי',
				'product.article.VodkaManhattanPineapple': 'וודקה מנהטן אננס',
				'product.article.BrandyMapleBrandyLouisXVDelicieuxBrand': 'ברנדי מייפל לואיס החמישי דליסיו ברנד',
				'product.article.BrandyCherryBrandyLouisXVDelicieuxBrand': 'ברנדי דובדבן לואיס החמישי דליסיו ברנד',
				'product.article.BrandyHoneyBrandyLouisXVDelicieuxBrand': 'ברנדי דבש לואיס החמישי דליסיו ברנד',
				'product.article.BrandyAppleBrandyLouisXVDelicieuxBrand': 'ברנדי תפוח לואיס החמישי דליסיו ברנד',
				'product.article.BrandyRoseBrandyLouisXVDelicieuxBrand': 'ברנדי רוזה לואיס החמישי דליסיו ברנד',
				'product.article.Beresheet.VodkaImperial': 'וודקה אימפריאל בראשית',
				'product.article.GiladAppleVilageWine': 'יין כפרי גלעד תפוח',
				'product.article.GiladCherryVilageWine': 'יין כפרי גלעד דובדבן',
				'product.article.GiladRaspberryVilageWine': 'יין כפרי גלעד פטל',
				'product.article.HarelBlueBerryVilageWine': 'יין כפרי חרמון תות כחול',
				'product.article.GILADLemonVilageWine': 'יין כפרי גלעד לימון',
				'product.article.HarelCurrantsVilageWine': 'יין כפרי חרמון דרים',
				'product.article.GILADApricot,': 'סדרת יינות פרי של גלעד',
				'product.article.GILADOrange,': 'סדרת יינות פרי של גלעד',
				'product.article.WineConvetoDaVilaRed,': 'יין קונווטו דה וילה אדום',
				'product.article.WineConvetoDaVilaBranco2023,': 'יין קונווטו דה וילה לבן 2023',
				'product.article.CognacMaximeTrijolXOGrandeChampagne': 'קוניאק מקסים טריג\'ול XO גרנד שמפניה',
				'product.article.CognacMaximeTrijolVSOPGrandeChampagne': 'קוניאק מקסים טריג\'ול VSOP גרנד שמפניה',
				'product.article.MaximeTrijolCognacVSOP750ML': 'קוניאק מקסים טריג\'ול VSOP 750 מ"ל',
				'product.article.MaximeTrijolCognacVS50ML': 'קוניאק מקסים טריג\'ול VS 50 מ"ל',
				'product.article.MaximeTrijolCognacXO50ML': 'קוניאק מקסים טריג\'ול XO 50 מ"ל',
				'product.article.MaximeTrijolCognacVSOP50ML': 'קוניאק מקסים טריג\'ול VSOP 50 מ"ל',
				'product.article.WineFiuzaNativeReservaWhite2018,': 'יין פיוזה נייטיב רזרבה לבן 2018',
				'product.article.MaximeTrijolCognacVSOP700ML': 'קוניאק מקסים טריג\'ול VSOP 700 מ"ל',
				'product.article.BrandyLouisXVDelicieuxBrand': 'זהו ברנדי עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 700 מ"ל.',
				'product.article.WineEasyFritzDurelloGleraWhite': 'זהו יין לבן עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.WineVelasCorsariasWhite': 'זהו יין לבן עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.WineRosatoFrizzante': 'זהו יין רוזה פריזנטה עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.GalitosWhite': 'זהו יין לבן יבש מברכת בראשית עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.GalitosRose': 'זהו יין רוזה יבש מברכת בראשית עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.GalitosTintoRegionalAlentejo': 'זהו יין אדום עשיר מאלנטג\'ו עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.VodkaRusStandart200ml': 'זהו וודקה פרימיום מרוסיה עם תווים פרותיים בולטים, נפח הבקבוק הוא 200 מ"ל.',
				'product.article.Beresheet.BrandyLouisXVFineOldBrand,wine': 'זהו ברנדי עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 175 מ"ל.',
				'product.article.Beresheet.BrandyLouisXVOrange,wine': 'זהו יין אדום עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 700 מ"ל.',
				'product.article.Beresheet.WineGrandNoirRose,wine': 'זהו יין רוזה חצי יבש מברכת בראשית עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.WineGeorgianAlazaniValleyWhiteSemiSweetwine': 'זהו יין לבן חצי מתוק מגאורגיה עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.WineGeorgianAlazaniValleyRedSemiSweet,.2023.wine': 'זהו יין אדום חצי מתוק מגאורגיה עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.BeresheetReserveMerilotShraz.2023.wine': 'זהו יין אדום עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.Port.2023.wine': 'זהו יין אדום עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.Beresheet.Reserve.2023.wine': 'זהו יין אדום עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'Beresheet Cabernet Sauvignon 2023': 'בֶּרֶשִׁית כַּבֶּרְנֵה סוֹבִינּוֹן 2023',
				'R.I.L.L Collection online storefront': 'חנות האינטרנט של R.I.L.L Collection',
				'ALL PRODUCTS': 'כל המוצרים',
				Description: 'תֵאוּר',
				'More Details': 'פרטים נוספים',
				'Alcohol Strength': 'כוח אלכוהול',
				Origin: 'מָקוֹר',
				'Phone number copied!': 'מספר הטלפון הועתק',
				Liquor: 'לִיקֵר 🥃',
				'We are on Facebook, Tiktok, & Instagram. You can also contact us via Email.': 'אנחנו בפייסבוק, טיקטוק ואינסטגרם. ניתן גם ליצור איתנו קשר באמצעות דוא"ל.',
				'Copy phone number': 'העתק מספר טלפון',
				'You must be over 18 to access this site.': 'עליך להיות מעל גיל 18 כדי לגשת לאתר זה.',
				'Access Denied': 'גישה נדחתה',
				'Bottle Volume': 'נפח בקבוקים',
				'product.article.Beresheet.Cabernet.2023.wine': 'זהו יין אדום עשיר מישראל עם תווים פרותיים בולטים, נפח הבקבוק הוא 750 מ"ל.',
				'Albergaria Limoncello Liquor 700ml': 'ליקר Albergaria Limoncello 700 מ"ל',
				'product.article.VodkaMoskva': 'וודקה מוסקבה היא וודקה פרימיום מישראל עם כוח אלכוהול של 35% ונפח של 175 מ"ל.',
				'product.article.VodkaIcePalace500ml': 'וודקה אייס פאלאס 500 מ"ל היא וודקה פרימיום מאוקראינה עם כוח אלכוהול של 40% ונפח של 500 מ"ל.',
				'product.article.VodkaPrimeBlanche': 'וודקה פריים בלאנש היא וודקה פרימיום מאוקראינה עם כוח אלכוהול של 40% ונפח של 500 מ"ל.',
				'product.article.VodkaPrimeNoir': 'וודקה פריים נואר היא וודקה פרימיום מאוקראינה עם כוח אלכוהול של 40% ונפח של 500 מ"ל.',
				'product.article.VodkaIcePalace': 'וודקה אייס פאלאס היא וודקה פרימיום מאוקראינה עם כוח אלכוהול של 40% ונפח של 1 ליטר.',
				'product.article.VodkaNepoborna': 'וודקה נפובורנה היא וודקה פרימיום מאוקראינה עם כוח אלכוהול של 40% ונפח של 700 מ"ל.',
				'product.article.VodkaRusStandart.1l': 'וודקה רוסית סטנדרט היא וודקה פרימיום מרוסיה עם כוח אלכוהול של 40% ונפח של 1 ליטר.',
				'product.article.CognacSikvaruli5': 'קוניאק פרימיום שעבר יישון של 5 שנים עם טעם עמוק ומורכב.',
				'product.article.Cognac.Sikvaruli': 'זהו קוניאק מעולה עם ארומה עשירה וטעם חלק.',
				'product.article.Taller.Beer': 'זו בירה מרעננת עם טעם חלק.',
				'product.article.KrauzerBrau.Beer': 'זו בירת גרמנית קלאסית עם טעם חלק ומרענן.',
				'product.article.Chernigivske': 'זו בירת פילזנר גרמנית נקייה ומרעננת עם מרירות מאוזנת.',
				'product.article.Superior.Beer': 'זו בירת סטאוט אירית עשירה וחזקה עם טעמי שיבולת שועל עמוקים.',
				'product.article.EichbaumPilsenerBeer': 'זו בירת פילזנר גרמנית נקייה ומרעננת עם מרירות מאוזנת.',
				'product.article.EichbaumHellBeer': 'זו בירה הלל גרמנית קלאסית',
				'product.article.arakLemon': 'זהו ערק מסורתי עם טעם לימון מרענן, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.arakOrange': 'זהו ערק מסורתי עם טעם תפוז מרענן, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.vodkinaPeach': 'זו וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.vodkinaOrange': 'זו וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.vodkinaLemon': 'זו וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.vodkinaYellow': 'זו וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.vodkinaMango': 'זהו וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.arakOrange': 'זהו ערק מסורתי עם טעם תפוז מרענן, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.maximeTrijolCognac3L': 'קוניאק מקסים טריגול 3 ליטר',
				'product.article.summerMerlotAllSeasonsCollection2020': 'זהו יין אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.spainVelasCorsarias': 'זהו יין אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.biancoCChardonnayAllSeasonsCollection2020': 'זהו יין שמנת עם דומיננטיות של שרדונטה ומניותיו של ארינטו.',
				'product.article.montesCarlosDOCAlentejoTinto2016': 'זהו יין אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.fiuzaMerilot2015': 'זהו יין אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.adegaDeBorba': 'זהו יין אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.fiuzaCabernet.Sauvignon' : 'זהו יין אדום עשיר עם גוף מלא וסיומת ארוכה, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.oceaniusProdutoDePortugal2019': 'זהו יין נהדר, המשלב תווי פירות טריים ורכות מאפיינים של יינות פורטוגזים',
				'product.article.fiuzaNativeReserva2018': 'זהו יין אלגנטי עם טעם עשיר, בו תווים של הקריקטורה שולטים, המשלימים את הרעננות המעודנת של ארינטו.',
				'product.article.maximeTrijolCognacSmall': 'קוניאק מקסים טריגול קטן',
				'product.article.maximeTrijolCognacVsop': 'קוניאק מקסים טריגול Vsop',
				'product.article.maximeTrijolCognacEiffelTower' : 'קוניאק מקסים טריגול אייפל טאוור',
				'product.article.VodkaRusStandart': 'וודקה רוסית סטנדרט היא וודקה פרימיום מרוסיה עם 40% אלכוהול ונפח של 1 ליטר.',
				'product.article.VodkaMoskva': 'וודקה מוסקבה היא וודקה פרימיום מישראל עם 35% אלכוהול ונפח של 175 מ"ל.',
				'product.article.VodkaManhattan': 'וודקה מנהטן היא וודקה פרימיום מישראל עם 37.5% אלכוהול ונפח של 700 מ"ל.',
				'product.article.VodkaIcePalace500': 'וודקה אייס פאלאס 500 מ"ל היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 500 מ"ל.',
				'product.article.VodkaPrimeBlanche': 'וודקה פריים בלאנש היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 500 מ"ל.',
				'product.article.VodkaPrimeNoir': 'וודקה פריים נואר היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 500 מ"ל.',
				'product.article.VodkaIcePalace': 'וודקה אייס פאלאס היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 1 ליטר.',
				'product.article.VodkaNepoborna': 'וודקה נפובורנה היא וודקה פרימיום מאוקראינה עם 40% אלכוהול ונפח של 700 מ"ל.',
				'product.article.EichbaumHell': 'בירה גרמנית קלאסית עם טעם חלק ומרענן.',
        'product.article.EichbaumPilsener': 'פילזנר גרמני פריך ונקי עם מרירות מאוזנת.',
        'product.article.Superior': 'סטאוט אירי עשיר וחזק עם טעמי לתת עמוקים.',
				'Wine Fiuza Native Reserva 2018': 'יין פיוזה רזרבת 2018',
				'Wine Oceanius Produto De Portugal 2019': 'מוצר יין אושניוס מפורטוגל 2019',
				'product.article.oceaniusProdutoDePortugal2019': 'זהו יין נהדר, המשלב תווי פירות טריים ורכות מאפיינים של יינות פורטוגזים',
				productarticlfiuzaChardonnayArinto:
				'זהו יין שמנת עם דומיננטיות של שרדונטה ומניותיו של ארינטו. ',
				'product.article.fiuzaNativeReserva2018': 'זהו יין אלגנטי עם טעם עשיר, בו תווים של הקריקטורה שולטים, המשלימים את הרעננות המעודנת של ארינטו.',
				'Warning about alcohol': 'אלכוהול מזיק לבריאותך!',
				'product.article.portoCabracoRose': 'זהו פורט ורוד מרענן עם ניחוחות פירותיים, נפח הבקבוק 750 מ"ל.',
				'product.article.portoCabracoWhite': 'זהו יין פורט אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				'product.article.portoCabracoRuby': 'זהו יין פורט אדום עשיר עם תווי פרי בהירים, נפח הבקבוק הוא 750 מ"ל.',
				warning:
					'אזהרה: צריכת אלכוהול מופרזת עלולה להזיק לבריאותך. אנא שתה באחריות',
				'Learn More': 'קרא עוד',
				'Discover the Finest Alcoholic Beverages at R.I.L.L Collection':
					'גלו את המשקאות האלכוהוליים הטובים ביותר ב-R.I.L.L Collection',
				'Best Alcohol from all over the world':
					'האלכוהול הטוב ביותר מכל רחבי העולם',
				'Open Catalog': 'פתח קטלוג',
				Catalog: 'קטלוג',
				'Get In Touch': 'צור קשר',
				'We are in Facebook, Tiktok, & Instagram. You can also contact us via Email.':
					'אנחנו בפייסבוק, בטיקטוק ובאינסטגרם. ניתן גם ליצור איתנו קשר באמצעות דוא"ל.',
				'Page Not Found': 'Страница не найдена',
				'Go Back Home': 'הדף לא נמצא',
				'Contact Us': 'צור קשר',
				Contact: 'צור קשר',
				Reviews: 'הדעת',
				'Wine Fiuza Chardonnay Arinto Native Reserva 2017': 'יין פיוזה שרדונה ארינטו יליד רזרבה 2017 ',
				'Alcohol 🍾': 'אלכוהול 🍾',
				Insights: 'תובנות',
				'Popular product categories': 'קטגוריות מוצרים פופולריות',
				Permalinks: 'קישורים קבועים',
				Blog: 'בלוג',
				Search: 'לחפש',
				Communities: 'קהילות',
				Vodkino: 'וודקה בטעמים',
				'Our Socials and contacts.': 'הרשתות החברתיות ואנשי הקשר שלנו.',
				'Our Catalog': 'הקטלוג שלנו',
				'Import and marketing of quality products.':
					'יבוא ושיווק מוצרים איכותיים.',
				'Street 8 Azur': 'החצב 8 אזור',
				'Postal code 5802920, Israel': 'מיקוד 5802920, ישראל',
				'Phone ☎: 03-6542200 Mobile 📱: 052-4448940':
					'טלפון ☎: 03-6542200 נייד 📱: 052-4448940',
				'Email: rillcollection2023@gmail.com':
					'מייל: rillcollection2023@gmail.com',
				'Page Not Found': 'הדף לא נמצא',
				Home: 'בית',
				'Welcome!': 'ברוכים הבאים!',
				'Verify that you are legal age.': 'ודא שאתה בגיל החוקי',
				"I'm above 18": 'אני מעל 18',
				"I'm under 18": 'אני מתחת ל 18',
				'All Categories': 'כל הקטגוריות',
				'Warning: contains alcohol, it is recommended to avoid excessive drinking':
					'אזהרה: מכיל אלכוהול מומלץ להימנע משתיה מופרזת',
				'Warning! Excessive consumption of alcohol is life-threatening and harmful to health':
					'אזהרה! צריכה מופרזת של אלכוהול מסכנת חיים ומזיקה לבריאות',
				'Port wine': 'יַיִן פּוֹרט',
			},
		},
	},
	lng: savedLanguage,
	fallbackLng: 'he',
	ns: ['translations'],
	defaultNS: 'translations',
	keySeparator: false,
	interpolation: {
		escapeValue: false,
		formatSeparator: ',',
	},
	react: {
		wait: true,
	},
})

const root = ReactDOM.createRoot(document.querySelector('#root'))

root.render(<App />)
